import type { Dialect } from '../type/index.js';

export interface DialectFeatures {
  returning: boolean;
  ifNotExists: boolean;
  indexIfNotExists: boolean;
  dropTableCascade: boolean;
  renameColumn: boolean;
  foreignKeyAlter: boolean;
}

export interface DialectConfig {
  quoteChar: '"' | '`';
  serialPrimaryKey: string;
  tableOptions: string;
  alterColumnSyntax: 'ALTER COLUMN' | 'MODIFY COLUMN' | 'none';
  dropForeignKeySyntax: 'DROP CONSTRAINT' | 'DROP FOREIGN KEY';
  beginTransactionCommand: string;
  commitTransactionCommand: string;
  rollbackTransactionCommand: string;
  features: DialectFeatures;
}

export const DIALECT_CONFIG: Record<Dialect, DialectConfig> = {
  postgres: {
    quoteChar: '"',
    serialPrimaryKey: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    tableOptions: '',
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    alterColumnSyntax: 'ALTER COLUMN',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: true,
      dropTableCascade: true,
      renameColumn: true,
      foreignKeyAlter: true,
    },
  },
  mysql: {
    quoteChar: '`',
    serialPrimaryKey: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    beginTransactionCommand: 'START TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    alterColumnSyntax: 'MODIFY COLUMN',
    dropForeignKeySyntax: 'DROP FOREIGN KEY',
    features: {
      returning: false,
      ifNotExists: true,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: true,
      foreignKeyAlter: true,
    },
  },
  mariadb: {
    quoteChar: '`',
    serialPrimaryKey: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    beginTransactionCommand: 'START TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    alterColumnSyntax: 'MODIFY COLUMN',
    dropForeignKeySyntax: 'DROP FOREIGN KEY',
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: true,
      foreignKeyAlter: true,
    },
  },
  sqlite: {
    quoteChar: '`',
    serialPrimaryKey: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    tableOptions: '',
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    alterColumnSyntax: 'none',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: true,
      foreignKeyAlter: false,
    },
  },
  mongodb: {
    quoteChar: '"',
    serialPrimaryKey: '',
    tableOptions: '',
    beginTransactionCommand: '',
    commitTransactionCommand: '',
    rollbackTransactionCommand: '',
    alterColumnSyntax: 'none',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    features: {
      returning: false,
      ifNotExists: false,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: false,
      foreignKeyAlter: false,
    },
  },
};

export function getDialectConfig(dialect: Dialect): DialectConfig {
  return DIALECT_CONFIG[dialect];
}
