import type { Dialect } from '../type/index.js';

export interface DialectConfig {
  quoteChar: '"' | '`';
  serialPrimaryKey: string;
  tableOptions: string;
  supportsReturning: boolean;
  supportsIfNotExists: boolean;
  alterColumnSyntax: 'ALTER COLUMN' | 'MODIFY COLUMN' | 'none';
  dropForeignKeySyntax: 'DROP CONSTRAINT' | 'DROP FOREIGN KEY';
  supportsRenameColumn: boolean;
  beginTransactionCommand: string;
  commitTransactionCommand: string;
  rollbackTransactionCommand: string;
}

export const DIALECT_CONFIG: Record<Dialect, DialectConfig> = {
  postgres: {
    quoteChar: '"',
    serialPrimaryKey: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    tableOptions: '',
    supportsReturning: true,
    supportsIfNotExists: true,
    alterColumnSyntax: 'ALTER COLUMN',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    supportsRenameColumn: true,
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
  },
  mysql: {
    quoteChar: '`',
    serialPrimaryKey: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    supportsReturning: false,
    supportsIfNotExists: true,
    alterColumnSyntax: 'MODIFY COLUMN',
    dropForeignKeySyntax: 'DROP FOREIGN KEY',
    supportsRenameColumn: true,
    beginTransactionCommand: 'START TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
  },
  mariadb: {
    quoteChar: '`',
    serialPrimaryKey: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    supportsReturning: true,
    supportsIfNotExists: true,
    alterColumnSyntax: 'MODIFY COLUMN',
    dropForeignKeySyntax: 'DROP FOREIGN KEY',
    supportsRenameColumn: true,
    beginTransactionCommand: 'START TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
  },
  sqlite: {
    quoteChar: '`',
    serialPrimaryKey: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    tableOptions: '',
    supportsReturning: true,
    supportsIfNotExists: true,
    alterColumnSyntax: 'none',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    supportsRenameColumn: true,
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
  },
  mongodb: {
    quoteChar: '"',
    serialPrimaryKey: '',
    tableOptions: '',
    supportsReturning: false,
    supportsIfNotExists: false,
    alterColumnSyntax: 'none',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    supportsRenameColumn: false,
    beginTransactionCommand: '',
    commitTransactionCommand: '',
    rollbackTransactionCommand: '',
  },
};

export function getDialectConfig(dialect: Dialect): DialectConfig {
  return DIALECT_CONFIG[dialect];
}
