import { describe, expect, it } from 'vitest';
import { Entity, Field, Id } from '../entity/index.js';
import type { Dialect } from '../type/index.js';
import { SqlSchemaGenerator } from './schemaGenerator.js';

describe('SqlSchemaGenerator (unified)', () => {
  const dialects: Dialect[] = ['postgres', 'mysql', 'mariadb', 'sqlite'];

  describe.each(dialects)('Dialect: %s', (dialect) => {
    const generator = new SqlSchemaGenerator(dialect);

    it('should generate correct CREATE TABLE SQL', () => {
      @Entity({ name: 'users' })
      class User {
        @Id() id?: number;
        @Field() name?: string;
      }

      const sql = generator.generateCreateTable(User);
      expect(sql).toContain('CREATE TABLE');
      expect(sql).toContain('users');
      expect(sql).toContain('id');
      expect(sql).toContain('name');

      if (dialect === 'postgres') {
        expect(sql).toContain('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
      } else if (dialect === 'mysql' || dialect === 'mariadb') {
        expect(sql).toContain('BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY');
        expect(sql).toContain('ENGINE=InnoDB');
      } else if (dialect === 'sqlite') {
        expect(sql).toContain('INTEGER PRIMARY KEY AUTOINCREMENT');
      }
    });

    it('should generate correct DROP TABLE SQL', () => {
      @Entity({ name: 'users' })
      class User {
        @Id() id?: number;
      }

      const sql = generator.generateDropTable(User);
      expect(sql).toContain('DROP TABLE IF EXISTS');
      expect(sql).toContain('users');
    });

    it('should generate correct SQL type for Boolean', () => {
      @Entity()
      class Test {
        @Id() id?: number;
        @Field() active?: boolean;
      }

      const sqlType = generator.getSqlType({ type: Boolean });
      if (dialect === 'postgres') {
        expect(sqlType).toBe('BOOLEAN');
      } else if (dialect === 'mysql' || dialect === 'mariadb') {
        expect(sqlType).toBe('TINYINT(1)');
      } else if (dialect === 'sqlite') {
        expect(sqlType).toBe('INTEGER');
      }
    });

    it('should generate correct column comments', () => {
      const comment = generator.generateColumnComment('col', 'Testing');
      if (dialect === 'mysql' || dialect === 'mariadb') {
        expect(comment).toBe(" COMMENT 'Testing'");
      } else {
        expect(comment).toBe('');
      }
    });
  });
});
