import { describe, expect, it } from 'vitest';
import { Entity, Field, Id, ManyToOne } from '../entity/index.js';
import type { ColumnType } from '../type/index.js';
import { isAutoIncrement } from '../util/index.js';
import { MysqlSchemaGenerator } from './generator/mysqlSchemaGenerator.js';
import { PostgresSchemaGenerator } from './generator/postgresSchemaGenerator.js';
import { SqliteSchemaGenerator } from './generator/sqliteSchemaGenerator.js';
import { AbstractSchemaGenerator } from './schemaGenerator.js';

// Test entities
@Entity()
class TestUser {
  @Id()
  id?: number;

  @Field({ length: 100 })
  name?: string;

  @Field({ unique: true })
  email?: string;

  @Field({ nullable: false })
  password?: string;

  @Field({ onInsert: Date.now })
  createdAt?: number;
}

@Entity({ name: 'blog_posts' })
class TestPost {
  @Id({ onInsert: () => crypto.randomUUID(), length: 36 })
  id?: string;

  @Field()
  title?: string;

  @Field({ columnType: 'text' })
  content?: string;

  @Field({ type: 'jsonb' })
  metadata?: Record<string, unknown>;

  @Field({ reference: () => TestUser })
  authorId?: number;

  @ManyToOne()
  author?: TestUser;
}

describe('PostgresSchemaGenerator', () => {
  const generator = new PostgresSchemaGenerator();

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateTable(TestUser);

    expect(sql).toContain('CREATE TABLE "TestUser"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('"name" VARCHAR(100)');
    expect(sql).toContain('"email" TEXT UNIQUE');
    expect(sql).toContain('"password" TEXT NOT NULL');
    expect(sql).toContain('"createdAt"');
  });

  it('should generate CREATE TABLE with UUID primary key', () => {
    const sql = generator.generateCreateTable(TestPost);

    expect(sql).toContain('CREATE TABLE "blog_posts"');
    expect(sql).toContain('"id" VARCHAR(36) PRIMARY KEY');
    expect(sql).toContain('"title" TEXT');
    expect(sql).toContain('"content" TEXT');
    expect(sql).toContain('"metadata" JSONB');
    expect(sql).toContain('"authorId"');
  });

  it('should generate DROP TABLE statement', () => {
    const sql = generator.generateDropTable(TestUser);

    expect(sql).toBe('DROP TABLE IF EXISTS "TestUser";');
  });

  it('should generate CREATE INDEX statement', () => {
    const sql = generator.generateCreateIndex('users', {
      name: 'idx_users_email',
      columns: ['email'],
      unique: true,
    });

    expect(sql).toBe('CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email");');
  });

  it('should generate CREATE TABLE with IF NOT EXISTS', () => {
    const sql = generator.generateCreateTable(TestUser, { ifNotExists: true });
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "TestUser"');
  });

  it('should handle embedded quotes in table names', () => {
    @Entity({ name: 'my"table' })
    class TestEntity {
      @Id()
      id?: number;
    }
    const sql = generator.generateCreateTable(TestEntity);
    expect(sql).toContain('CREATE TABLE "my""table"');
  });

  it('should handle already-typed column schemas', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    // Should NOT be JSONB(JSONB)
    expect(sql[0]).toContain('ADD COLUMN "profile_data" JSONB');
    expect(sql[0]).not.toContain('JSONB(');
  });

  it('should generate ALTER TABLE DOWN statements', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    expect(sql[0]).toBe('ALTER TABLE "users" DROP COLUMN "profile_data";');
  });
});

describe('MysqlSchemaGenerator', () => {
  const generator = new MysqlSchemaGenerator();

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateTable(TestUser);

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY');
    expect(sql).toContain('`name` VARCHAR(100)');
    expect(sql).toContain('`email` VARCHAR(255) UNIQUE');
    expect(sql).toContain('ENGINE=InnoDB');
  });

  it('should generate boolean as TINYINT(1)', () => {
    const boolType = generator.getSqlType({ type: Boolean }, Boolean);
    expect(boolType).toBe('TINYINT(1)');
  });

  it('should generate DROP INDEX with ON table', () => {
    const sql = generator.generateDropIndex('users', 'idx_email');
    expect(sql).toBe('DROP INDEX `idx_email` ON `users`;');
  });
});

describe('SqliteSchemaGenerator', () => {
  const generator = new SqliteSchemaGenerator();

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateTable(TestUser);

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` INTEGER PRIMARY KEY AUTOINCREMENT');
    // SQLite uses VARCHAR when length is specified, which is fine as SQLite has dynamic typing
    expect(sql).toContain('`name` TEXT');
    expect(sql).toContain('`email` TEXT UNIQUE');
  });

  it('should use TEXT for most types (SQLite dynamic typing)', () => {
    expect(generator.getSqlType({ columnType: 'varchar' }, String)).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'json' }, undefined)).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'uuid' }, undefined)).toBe('TEXT');
  });

  it('should use INTEGER for numeric types', () => {
    expect(generator.getSqlType({ columnType: 'int' }, undefined)).toBe('INTEGER');
    expect(generator.getSqlType({ columnType: 'bigint' }, undefined)).toBe('INTEGER');
    expect(generator.getSqlType({ type: Boolean }, Boolean)).toBe('INTEGER');
  });
});

describe('AbstractSchemaGenerator.isAutoIncrement', () => {
  it('should return true for numeric primary keys', () => {
    expect(isAutoIncrement({ type: Number }, true)).toBe(true);
    expect(isAutoIncrement({ type: 'number' }, true)).toBe(true);
    expect(isAutoIncrement({ type: BigInt }, true)).toBe(true);
    expect(isAutoIncrement({ type: 'bigint' }, true)).toBe(true);
    expect(isAutoIncrement({ type: Number, autoIncrement: true }, true)).toBe(true);
  });

  it('should return false if not a primary key', () => {
    expect(isAutoIncrement({ type: Number }, false)).toBe(false);
  });

  it('should return false for non-numeric types', () => {
    expect(isAutoIncrement({ type: String }, true)).toBe(false);
    expect(isAutoIncrement({ type: Date }, true)).toBe(false);
  });

  it('should return false if autoIncrement is explicitly false', () => {
    expect(isAutoIncrement({ type: Number, autoIncrement: false }, true)).toBe(false);
  });

  it('should return false if onInsert is present', () => {
    expect(isAutoIncrement({ type: Number, onInsert: () => 1 }, true)).toBe(false);
  });

  it('should return false if columnType is explicitly set', () => {
    expect(isAutoIncrement({ type: Number, columnType: 'int' }, true)).toBe(false);
  });
});

describe('AbstractSchemaGenerator.coverage', () => {
  class MockGenerator extends AbstractSchemaGenerator {
    protected serialPrimaryKeyType = 'SERIAL PRIMARY KEY';
    mapColumnType(columnType: ColumnType): string {
      return columnType.toUpperCase();
    }
    getBooleanType(): string {
      return 'BOOLEAN';
    }
    generateAlterColumnStatements(): string[] {
      return [];
    }
    generateColumnComment(): string {
      return '';
    }
  }
  const generator = new MockGenerator();

  it('should generate DROP INDEX (base)', () => {
    expect(generator.generateDropIndex('users', 'idx_email')).toBe('DROP INDEX IF EXISTS `idx_email`;');
  });

  it('should handle generateColumnDefinitionFromSchema for manual PK', () => {
    const col: any = { name: 'id', type: 'INT', isPrimaryKey: true, nullable: false };
    const sql = generator.generateColumnDefinitionFromSchema(col);
    expect(sql).toContain('INT PRIMARY KEY');
  });

  it('should handle defaultValue in generateColumnDefinition', () => {
    @Entity()
    class TestDefault {
      @Id() id: number;
      @Field({ defaultValue: 'active' }) status: string;
    }
    const sql = generator.generateCreateTable(TestDefault);
    expect(sql).toContain("`status` VARCHAR DEFAULT 'active'");
  });

  it('should normalize non-string defaults', () => {
    @Entity()
    class NumberDefault {
      @Id() id: number;
      @Field({ defaultValue: 123 }) val: number;
    }
    const current = {
      name: 'NumberDefault',
      columns: [
        {
          name: 'id',
          type: 'SERIAL PRIMARY KEY',
          isPrimaryKey: true,
          isAutoIncrement: true,
          nullable: false,
          isUnique: false,
        },
        {
          name: 'val',
          type: 'BIGINT',
          defaultValue: 123,
          isPrimaryKey: false,
          isAutoIncrement: false,
          nullable: true,
          isUnique: false,
        },
      ],
    };
    const diff = generator.diffSchema(NumberDefault, current as any);
    expect(diff).toBeUndefined();
  });

  it('should normalize boolean defaults', () => {
    @Entity()
    class BoolDefault {
      @Id() id: number;
      @Field({ defaultValue: true }) val: boolean;
    }
    const current = {
      name: 'BoolDefault',
      columns: [
        {
          name: 'id',
          type: 'SERIAL PRIMARY KEY',
          isPrimaryKey: true,
          isAutoIncrement: true,
          nullable: false,
          isUnique: false,
        },
        {
          name: 'val',
          type: 'BOOLEAN',
          defaultValue: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          nullable: true,
          isUnique: false,
        },
      ],
    };
    const diff = generator.diffSchema(BoolDefault, current as any);
    expect(diff).toBeUndefined();
  });

  it('should handle numeric/decimal columnType (Postgres)', () => {
    const pg = new PostgresSchemaGenerator();
    expect(pg.mapColumnType('numeric', {})).toBe('NUMERIC');
    expect(pg.mapColumnType('decimal', { precision: 10 })).toBe('NUMERIC(10)');
    expect(pg.mapColumnType('decimal', { precision: 10, scale: 2 })).toBe('NUMERIC(10, 2)');
    expect(pg.mapColumnType('int', {})).toBe('INTEGER');
    expect(pg.mapColumnType('smallint', {})).toBe('SMALLINT');
  });
});
